const text = [
  `In the heart of a bustling city, where dreams intertwine with the rhythm of life, there exists a hidden sanctuary known only to a select few. This sanctuary, nestled amidst the chaos of urban existence, is a place of refuge and contemplation. Here, time seems to slow down, and the worries of the world melt away. The air is thick with the scent of jasmine and sandalwood, and the sound of distant laughter drifts through the streets like a sweet melody. Within the sanctuary's walls, ancient trees stand tall, their branches reaching towards the heavens. Shafts of sunlight filter through the leaves, casting dappled shadows on the ground below. It is a place of serenity and peace, a haven from the frenetic pace of modern life.`,
  `Deep within the heart of the forest, where the trees stand tall and proud, there lies a hidden glade untouched by the hands of man. Here, the air is cool and crisp, filled with the scent of pine and earth. Sunlight filters through the canopy above, casting a warm glow on the moss-covered ground below. Butterflies flit through the air, their delicate wings shimmering in the sunlight. Birds sing sweetly in the treetops, their songs echoing through the forest like a symphony. In this tranquil oasis, time seems to stand still, and the worries of the world fade away. It is a place of pure magic, where nature reigns supreme and the soul finds solace in the beauty of the natural world.`,
  `High atop a windswept cliff, overlooking the vast expanse of the ocean, there stands a solitary lighthouse, its beacon cutting through the darkness like a guiding star. This beacon of hope stands as a sentinel against the raging sea, a symbol of strength and resilience in the face of adversity. From its lofty perch, the lighthouse keeper keeps watch over the horizon, scanning the endless waves for signs of danger. Below, the waves crash against the rocky shore, sending plumes of spray into the air. Seagulls wheel overhead, their cries mingling with the sound of the surf. In this remote outpost, far from the noise and chaos of the world below, the lighthouse keeper finds peace amidst the storm.`,
  `In the heart of the desert, where the sun beats down relentlessly and the sand stretches out as far as the eye can see, there exists an oasis of life amidst the barren wasteland. Here, amidst the shimmering heat, stands a cluster of palm trees, their fronds swaying gently in the breeze. Beneath their shade, a pool of cool, clear water beckons to weary travelers, offering refreshment and respite from the relentless sun. Around the pool, vibrant flowers bloom, their petals a riot of color against the backdrop of endless sand. Birds flit through the branches, their songs filling the air with music. In this harsh and unforgiving landscape, the oasis stands as a symbol of hope and renewal, a reminder that life can thrive even in the most unlikely of places.`,
  `At the edge of the world, where the sky meets the sea in a breathtaking display of color, there lies a hidden island, shrouded in mystery and legend. This island, surrounded by treacherous reefs and swirling mists, is a place of wonder and enchantment. Its shores are lined with golden beaches, lapped by crystal-clear waters teeming with life. Inland, dense jungles teem with exotic plants and animals, their vibrant colors a feast for the eyes. Waterfalls cascade down rocky cliffs, their roar echoing through the valleys below. At the heart of the island stands a towering volcano, its peak wreathed in smoke and flame. It is a place of danger and beauty, of adventure and discovery, where the brave and the bold come in search of fortune and glory.`,
  `In the heart of the mountains, where the air is thin and the snow-capped peaks reach towards the sky, there exists a hidden valley, untouched by the hand of man. Here, amidst the rugged beauty of the wilderness, life flourishes in abundance. Tall pine trees stand sentinel against the elements, their branches laden with snow. Deer and elk roam freely through the forest, their tracks crisscrossing the snowy landscape. Eagles soar overhead, their cries echoing through the valleys below. In this remote paradise, far from the noise and chaos of the world below, the soul finds solace in the beauty of nature, and the spirit is renewed by the majesty of the mountains.`,
  `Deep beneath the surface of the earth, where darkness reigns supreme and the air is heavy with the scent of damp earth, there lies a hidden realm, untouched by the light of day. This subterranean world is a labyrinth of twisting tunnels and caverns, its depths home to strange and wondrous creatures. Blind fish swim in underground rivers, their ghostly forms shimmering in the darkness. Pale insects scuttle across the rocky floor, their antennae twitching as they search for food. In the deepest recesses of the caverns, strange formations of stalactites and stalagmites twist and turn like frozen rivers of stone. It is a world of mystery and wonder, where the echoes of time reverberate through the silent halls, and the secrets of the earth are hidden from prying eyes.`,
  `In the heart of the jungle, where the air is thick with humidity and the canopy above blocks out the sun, there exists a hidden temple, lost to the passage of time. This ancient temple, built by a long-forgotten civilization, is a testament to the ingenuity and skill of its creators. Its walls are adorned with intricate carvings depicting scenes from myth and legend, their meaning lost to the ages. Vines creep across the crumbling stone, their tendrils reaching towards the sky. In the inner sanctum of the temple, a golden idol sits atop a stone pedestal, its eyes gleaming with an otherworldly light. It is a place of mystery and danger, where the brave and the foolish come in search of treasure and glory, only to be consumed by the secrets of the past.`,
  `On the edge of a windswept moor, where the heather blooms in shades of purple and gold, there lies a hidden village, its thatched cottages nestled amidst the rolling hills. This idyllic hamlet, far from the noise and bustle of the city, is a place of peace and tranquility. Smoke curls from the chimneys of the cottages, carrying with it the scent of woodsmoke and baking bread. Sheep graze in the fields, their woolly coats a patchwork of white and black. In the village square, a market springs to life, its stalls laden with fresh produce and handmade goods. It is a place out of time, where the old ways still hold sway, and the simple pleasures of life are cherished above all else.`,
  `In the heart of the savannah, where the grasslands stretch out as far as the eye can see, there exists a hidden watering hole, a lifeline in the vast expanse of the wilderness. Here, beneath the blazing sun, animals of all shapes and sizes gather to drink, their thirst quenched by the cool, clear water. Elephants trumpet as they bathe in the shallows, their massive forms casting shadows on the muddy banks. Giraffes crane their necks to reach the water, their long tongues lapping greedily at the surface. Lions lounge in the shade of nearby trees, their golden coats gleaming in the sunlight. It is a place of life and death, where the struggle for survival plays out against the backdrop of the endless plains.`,
];

export default text;
